2023/01/21 13:29:36 [error] [exception.CException] CException: Property "CUrlManager.enableStrictParsing" is not defined. in C:\xampp\htdocs\yii1\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii1\YiiBase.php(227): CComponent->__set('enableStrictPar...', true)
#1 C:\xampp\htdocs\yii1\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii1\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\yii1\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/index.php/site/login
HTTP_REFERER=http://yii1.loc/index.php/site/index
---
2023/01/21 13:29:43 [error] [exception.CException] CException: Property "CUrlManager.enableStrictParsing" is not defined. in C:\xampp\htdocs\yii1\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii1\YiiBase.php(227): CComponent->__set('enableStrictPar...', true)
#1 C:\xampp\htdocs\yii1\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii1\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\yii1\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/index.php/site/index
HTTP_REFERER=http://yii1.loc/index.php/site/login
---
2023/01/21 14:26:29 [error] [exception.CException] CException: The URL pattern "<action:(login|logout|contact|about>" for route "site/<action>" is not a valid regular expression. in C:\xampp\htdocs\yii1\web\CUrlManager.php:716
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CUrlManager.php(270): CUrlRule->__construct('site/<action>', '<action:(login|...')
#1 C:\xampp\htdocs\yii1\web\CUrlManager.php(226): CUrlManager->createUrlRule('site/<action>', '<action:(login|...')
#2 C:\xampp\htdocs\yii1\web\CUrlManager.php(206): CUrlManager->processRules()
#3 C:\xampp\htdocs\yii1\base\CModule.php(394): CUrlManager->init()
#4 C:\xampp\htdocs\yii1\base\CApplication.php(531): CModule->getComponent('urlManager')
#5 C:\xampp\htdocs\yii1\web\CWebApplication.php(140): CApplication->getUrlManager()
#6 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#7 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/index.php/contact
HTTP_REFERER=http://yii1.loc/index.php/login
---
2023/01/21 14:51:19 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "about". in C:\xampp\htdocs\yii1\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(270): CController->missingAction('about')
#1 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('about')
#2 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/about')
#3 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/about
HTTP_REFERER=http://yii1.loc/index.php/
---
2023/01/21 14:54:26 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "about". in C:\xampp\htdocs\yii1\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(270): CController->missingAction('about')
#1 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('about')
#2 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/about')
#3 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/about
HTTP_REFERER=http://yii1.loc/index.php/
---
2023/01/21 15:11:53 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "about". in C:\xampp\htdocs\yii1\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(270): CController->missingAction('about')
#1 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('about')
#2 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/about')
#3 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/about
HTTP_REFERER=http://yii1.loc/index.php/
---
2023/01/21 15:21:24 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii1.loc/index.php/
---
2023/01/21 15:21:27 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/about". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/about')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/about
HTTP_REFERER=http://yii1.loc/index.php/
---
2023/01/21 15:21:39 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/contact". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/contact')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/contact
HTTP_REFERER=http://yii1.loc/index.php/
---
2023/01/21 15:22:35 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/contact". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/contact')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/contact
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 15:33:12 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/about". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/about')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/about
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 15:33:53 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/about". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/about')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/about
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 15:34:11 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/login". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/login')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/login
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 15:40:12 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/about". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/about')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/about
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 15:40:28 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/about". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/about')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/about
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 15:40:34 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/contact". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/contact')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/contact
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 15:42:00 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/about". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/about')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/about
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 15:43:21 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/about". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/about')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/about
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 15:47:26 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "public/about". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('public/about')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/about
HTTP_REFERER=http://yii1.loc/
---
2023/01/21 16:00:30 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "popup". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('popup')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/popup
---
2023/01/21 16:01:07 [error] [exception.CException] CException: SiteController cannot find the requested view "popup". in C:\xampp\htdocs\yii1\web\CController.php:881
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(785): CController->renderPartial('popup', NULL, true)
#1 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(110): CController->render('popup')
#2 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(49): SiteController->actionPopup()
#3 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('popup')
#7 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/popup')
#8 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/popup
---
2023/01/22 10:21:08 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii1.loc/
---
2023/01/22 10:47:19 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii1.loc/popup
---
2023/01/22 11:49:49 [error] [exception.CException] CException: Property "SiteController.widget" is not defined. in C:\xampp\htdocs\yii1\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii1\public\protected\views\site\popup.php(11): CComponent->__get('widget')
#1 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\yii1\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, true)
#3 C:\xampp\htdocs\yii1\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii1\web\CController.php(785): CController->renderPartial('popup', NULL, true)
#5 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(110): CController->render('popup')
#6 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(49): SiteController->actionPopup()
#7 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('popup')
#11 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/popup')
#12 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/popup
---
2023/01/22 13:12:30 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii1\web\CController.php:337
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('popup')
#4 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/popup')
#5 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/popup
---
2023/01/22 13:12:38 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "popup/1". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('popup/1')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/popup/1
---
2023/01/22 13:13:01 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii1\web\CController.php:337
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('popup')
#4 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/popup')
#5 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/popup/1
---
2023/01/22 13:14:37 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii1\web\CController.php:337
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('popup')
#4 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/popup')
#5 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/popup/1
---
2023/01/22 13:16:15 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii1\web\CController.php:337
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('popup')
#4 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/popup')
#5 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/popup/1
---
2023/01/22 13:17:28 [error] [exception.CException] CException: The URL pattern "<action:(popup)/<id:\d+>" for route "site/<action>" is not a valid regular expression. in C:\xampp\htdocs\yii1\web\CUrlManager.php:716
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CUrlManager.php(270): CUrlRule->__construct('site/<action>', '<action:(popup)...')
#1 C:\xampp\htdocs\yii1\web\CUrlManager.php(226): CUrlManager->createUrlRule('site/<action>', '<action:(popup)...')
#2 C:\xampp\htdocs\yii1\web\CUrlManager.php(206): CUrlManager->processRules()
#3 C:\xampp\htdocs\yii1\base\CModule.php(394): CUrlManager->init()
#4 C:\xampp\htdocs\yii1\base\CApplication.php(531): CModule->getComponent('urlManager')
#5 C:\xampp\htdocs\yii1\web\CWebApplication.php(140): CApplication->getUrlManager()
#6 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#7 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/popup/1
---
2023/01/22 13:18:01 [error] [exception.CException] CException: The URL pattern "<action:(popup|test)/<id:\d+>" for route "site/<action>" is not a valid regular expression. in C:\xampp\htdocs\yii1\web\CUrlManager.php:716
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CUrlManager.php(270): CUrlRule->__construct('site/<action>', '<action:(popup|...')
#1 C:\xampp\htdocs\yii1\web\CUrlManager.php(226): CUrlManager->createUrlRule('site/<action>', '<action:(popup|...')
#2 C:\xampp\htdocs\yii1\web\CUrlManager.php(206): CUrlManager->processRules()
#3 C:\xampp\htdocs\yii1\base\CModule.php(394): CUrlManager->init()
#4 C:\xampp\htdocs\yii1\base\CApplication.php(531): CModule->getComponent('urlManager')
#5 C:\xampp\htdocs\yii1\web\CWebApplication.php(140): CApplication->getUrlManager()
#6 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#7 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/popup/1
---
2023/01/22 13:18:57 [error] [php] compact(): Undefined variable $1 (C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php:110)
Stack trace:
#0 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(110): compact()
#1 unknown(0): SiteController->actionPopup()
#2 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs()
#3 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#4 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii1\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii1\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii1\public\index.php(13): CWebApplication->run()
REQUEST_URI=/popup/1
2023/01/22 13:23:02 [error] [exception.CException] CException: PopupWidget and its behaviors do not have a method or closure named "getBody". in C:\xampp\htdocs\yii1\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii1\public\protected\extensions\widgets\PopupWidget.php(7): CComponent->__call('getBody', Array)
#1 C:\xampp\htdocs\yii1\web\CBaseController.php(182): PopupWidget->run()
#2 C:\xampp\htdocs\yii1\public\protected\views\site\popup.php(11): CBaseController->widget('ext.widgets.Pop...', Array)
#3 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\yii1\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii1\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii1\web\CController.php(785): CController->renderPartial('popup', Array, true)
#7 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(110): CController->render('popup', Array)
#8 [internal function]: SiteController->actionPopup('1')
#9 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#10 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#11 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('popup')
#15 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/popup')
#16 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/popup/1
---
2023/01/22 14:12:57 [error] [exception.CException] CException: CHttpRequest and its behaviors do not have a method or closure named "baseUrl". in C:\xampp\htdocs\yii1\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii1\public\protected\views\site\popup.php(9): CComponent->__call('baseUrl', Array)
#1 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\yii1\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii1\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii1\web\CController.php(785): CController->renderPartial('popup', Array, true)
#5 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(110): CController->render('popup', Array)
#6 [internal function]: SiteController->actionPopup('6')
#7 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#8 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#9 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('popup')
#13 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/popup')
#14 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/popup/6
---
2023/01/22 15:04:01 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in C:\xampp\htdocs\yii1\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii1\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii1\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii1\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii1\cli\commands\MigrateCommand.php(472): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii1\cli\commands\MigrateCommand.php(481): MigrateCommand->getDbConnection()
#5 C:\xampp\htdocs\yii1\cli\commands\MigrateCommand.php(512): MigrateCommand->getMigrationHistory(-1)
#6 C:\xampp\htdocs\yii1\cli\commands\MigrateCommand.php(84): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp(Array)
#8 C:\xampp\htdocs\yii1\console\CConsoleCommand.php(178): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#9 C:\xampp\htdocs\yii1\console\CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#10 C:\xampp\htdocs\yii1\console\CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#11 C:\xampp\htdocs\yii1\base\CApplication.php(185): CConsoleApplication->processRequest()
#12 C:\xampp\htdocs\yii1\yiic.php(33): CApplication->run()
#13 C:\xampp\htdocs\yii1\public\protected\yiic.php(7): require_once('C:\\xampp\\htdocs...')
#14 C:\xampp\htdocs\yii1\public\protected\yiic(4): require_once('C:\\xampp\\htdocs...')
#15 {main}
---
2023/01/22 15:40:06 [error] [exception.CException] CException: Property "Popup.Включен" is not defined. in C:\xampp\htdocs\yii1\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii1\db\ar\CActiveRecord.php(145): CComponent->__get('\xD0\x92\xD0\xBA\xD0\xBB\xD1\x8E\xD1\x87\xD0\xB5\xD0\xBD')
#1 C:\xampp\htdocs\yii1\web\helpers\CHtml.php(2784): CActiveRecord->__get('\xD0\x92\xD0\xBA\xD0\xBB\xD1\x8E\xD1\x87\xD0\xB5\xD0\xBD')
#2 C:\xampp\htdocs\yii1\web\helpers\CHtml.php(2008): CHtml::resolveValue(Object(Popup), '\xD0\x92\xD0\xBA\xD0\xBB\xD1\x8E\xD1\x87\xD0\xB5\xD0\xBD')
#3 C:\xampp\htdocs\yii1\web\widgets\CActiveForm.php(915): CHtml::activeDropDownList(Object(Popup), '\xD0\x92\xD0\xBA\xD0\xBB\xD1\x8E\xD1\x87\xD0\xB5\xD0\xBD', Array, Array)
#4 C:\xampp\htdocs\yii1\public\protected\views\popup\_form.php(30): CActiveForm->dropDownList(Object(Popup), '\xD0\x92\xD0\xBA\xD0\xBB\xD1\x8E\xD1\x87\xD0\xB5\xD0\xBD', Array, Array)
#5 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii1\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii1\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii1\public\protected\views\popup\update.php(21): CController->renderPartial('_form', Array)
#9 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\yii1\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#11 C:\xampp\htdocs\yii1\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii1\web\CController.php(785): CController->renderPartial('update', Array, true)
#13 C:\xampp\htdocs\yii1\public\protected\controllers\PopupController.php(101): CController->render('update', Array)
#14 [internal function]: PopupController->actionUpdate('1')
#15 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs(Object(PopupController), Array)
#16 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PopupController), Object(ReflectionMethod), Array)
#17 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\yii1\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\yii1\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\yii1\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\yii1\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\yii1\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\yii1\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('update')
#26 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('popup/update/id...')
#27 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#28 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/popup/update/id/1
HTTP_REFERER=http://yii1.loc/popup/view/id/1
---
2023/01/22 16:01:32 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "remote". in C:\xampp\htdocs\yii1\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(270): CController->missingAction('remote')
#1 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('remote')
#2 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/remote')
#3 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/remote/2
---
2023/01/22 16:02:10 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "remote". in C:\xampp\htdocs\yii1\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CController.php(270): CController->missingAction('remote')
#1 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('remote')
#2 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/remote')
#3 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/remote/2
---
2023/01/22 16:02:20 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "remote". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('remote')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/remote/
---
2023/01/22 16:02:46 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "remote". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('remote')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/remote/
---
2023/01/22 19:03:55 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "remote/". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('remote/')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/remote//
HTTP_REFERER=http://localhost:4000/
---
2023/01/22 19:04:12 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "remote/". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('remote/')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/remote//
HTTP_REFERER=http://localhost:4000/
---
2023/01/22 19:19:52 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii1.loc/
---
2023/01/23 15:28:33 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in C:\xampp\htdocs\yii1\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://yii1.loc/
---
2023/01/23 15:56:51 [error] [php] Undefined variable $popup (C:\xampp\htdocs\yii1\public\protected\views\site\remote.php:11)
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii1\web\CBaseController.php(95): SiteController->renderInternal()
#2 C:\xampp\htdocs\yii1\web\CController.php(872): SiteController->renderFile()
#3 C:\xampp\htdocs\yii1\web\CController.php(785): SiteController->renderPartial()
#4 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(125): SiteController->render()
#5 unknown(0): SiteController->actionRemote()
#6 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs()
#7 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\yii1\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\yii1\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\yii1\public\index.php(13): CWebApplication->run()
REQUEST_URI=/remote/5
2023/01/23 16:27:49 [error] [exception.ParseError] ParseError: syntax error, unexpected token "}", expecting "," or ";" in C:\xampp\htdocs\yii1\public\protected\views\site\remote.php:21
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#1 C:\xampp\htdocs\yii1\web\CController.php(872): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\yii1\web\CController.php(785): CController->renderPartial('remote', Array, true)
#3 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(125): CController->render('remote', Array)
#4 [internal function]: SiteController->actionRemote('5')
#5 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#6 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#7 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): CController->run('remote')
#11 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController('site/remote')
#12 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\yii1\public\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/remote/5
---
2023/01/23 16:34:10 [error] [php] Using ${var} in strings is deprecated, use {$var} instead (C:\xampp\htdocs\yii1\public\protected\views\site\remote.php:14)
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii1\web\CBaseController.php(95): SiteController->renderInternal()
#2 C:\xampp\htdocs\yii1\web\CController.php(872): SiteController->renderFile()
#3 C:\xampp\htdocs\yii1\web\CController.php(785): SiteController->renderPartial()
#4 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(125): SiteController->render()
#5 unknown(0): SiteController->actionRemote()
#6 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs()
#7 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\yii1\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\yii1\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\yii1\public\index.php(13): CWebApplication->run()
REQUEST_URI=/remote/5
2023/01/23 16:34:44 [error] [php] Using ${var} in strings is deprecated, use {$var} instead (C:\xampp\htdocs\yii1\public\protected\views\site\remote.php:14)
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii1\web\CBaseController.php(95): SiteController->renderInternal()
#2 C:\xampp\htdocs\yii1\web\CController.php(872): SiteController->renderFile()
#3 C:\xampp\htdocs\yii1\web\CController.php(785): SiteController->renderPartial()
#4 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(125): SiteController->render()
#5 unknown(0): SiteController->actionRemote()
#6 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs()
#7 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\yii1\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\yii1\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\yii1\public\index.php(13): CWebApplication->run()
REQUEST_URI=/remote/6
2023/01/23 17:34:20 [error] [php] Undefined variable $Yii (C:\xampp\htdocs\yii1\public\protected\views\site\remote.php:12)
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii1\web\CBaseController.php(95): SiteController->renderInternal()
#2 C:\xampp\htdocs\yii1\web\CController.php(872): SiteController->renderFile()
#3 C:\xampp\htdocs\yii1\web\CController.php(785): SiteController->renderPartial()
#4 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(125): SiteController->render()
#5 unknown(0): SiteController->actionRemote()
#6 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs()
#7 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\yii1\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\yii1\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\yii1\public\index.php(13): CWebApplication->run()
REQUEST_URI=/remote/5
2023/01/23 17:36:47 [error] [php] Undefined variable $httpremote (C:\xampp\htdocs\yii1\public\protected\views\site\remote.php:18)
Stack trace:
#0 C:\xampp\htdocs\yii1\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii1\web\CBaseController.php(95): SiteController->renderInternal()
#2 C:\xampp\htdocs\yii1\web\CController.php(872): SiteController->renderFile()
#3 C:\xampp\htdocs\yii1\web\CController.php(785): SiteController->renderPartial()
#4 C:\xampp\htdocs\yii1\public\protected\controllers\SiteController.php(125): SiteController->render()
#5 unknown(0): SiteController->actionRemote()
#6 C:\xampp\htdocs\yii1\web\actions\CAction.php(115): ReflectionMethod->invokeArgs()
#7 C:\xampp\htdocs\yii1\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 C:\xampp\htdocs\yii1\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\yii1\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\yii1\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\yii1\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\yii1\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\yii1\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\yii1\public\index.php(13): CWebApplication->run()
REQUEST_URI=/remote/5
2023/01/23 18:11:42 [warning] [application] Failed to set unsafe attribute "counter" of "Popup".
2023/01/23 18:11:52 [warning] [application] Failed to set unsafe attribute "counter" of "Popup".
2023/01/23 18:12:00 [warning] [application] Failed to set unsafe attribute "counter" of "Popup".
2023/01/23 18:12:09 [warning] [application] Failed to set unsafe attribute "counter" of "Popup".
2023/01/23 18:12:21 [warning] [application] Failed to set unsafe attribute "counter" of "Popup".
